name: Deploy scaladoc
on:
  push:
    branches:
      - master
    
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Generate scaladoc for amyc-compiler
        run: sbt amyc-compiler/doc     
  upload-artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses:  actions/upload-pages-artifact@v0
        with:
          name: "amy-compiler_scaladoc_${{ github.head_ref }}.${{ github.sha }}"
          path: "compiler/target/scala-3.1.3/api"
