name: Deploy scaladoc
on:
  workflow_dispatch
  #push:
  #  branches:
  #    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Generate scaladoc for amyc-compiler
        run: sbt amy-compiler/doc 
      - uses:  actions/upload-pages-artifact@v1
        with:
          name: "amy-compiler_scaladoc_${{ github.head_ref }}.${{ github.sha }}"
          path: "compiler/target/scala-3.1.3/api"
          
  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: "${{ steps.deployment.outputs.page_url }}scaladoc/"

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
